config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'castles#index'
  resources :castles, only: [:index,:show]
  resources :twopage, only: [:index]
  resources :threepage, only: [:index]
  resources :posts, only: [:index, :show]
  
  resources :users, only: [:show]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/citadel.rb
class Citadel < ApplicationRecord
  belongs_to  :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many  :citadels
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/castles_controller.rb
class CastlesController < ApplicationController

  before_action :move_to_index, except: [:index]

  def index
    @citadel = Citadel.order("created_at DESC").page(params[:page]).per(12)
  end

  def show
    # binding.pry
    @citadel = Citadel.find(params[:id])
  end

  def new
  end

  
  def create
    Citadel.create(name: citadel_params[:name], image: citadel_params[:image],text: citadel_params[:text], user_id: current_user.id)
  end

  private
  def citadel_params
    params.permit(:name, :image, :text)
  end

  def move_to_index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def post_params
    params.require(:post).permit(:content)
end
end

app/controllers/threepage_controller.rb
class ThreepageController < ApplicationController
  def index
  end
end

app/controllers/twopage_controller.rb
class TwopageController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
    @nickname = current_user.nickname
    @citadels = Citadel.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/castles/_topp.html.haml
.top-pape
  %header.top-pape__site
    %h1.top-pape__site_title
      %a{href: "/"}Castle
      .top-pape__site_title__user
      - if user_signed_in?
        .top-pape__site_title__user_out
          = link_to "ログアウト", destroy_user_session_path, method: :delete
      - else
        .top-pape__site_title__user_new
          = link_to "ログイン", new_user_session_path, class: 'post'
          = link_to "登録", new_user_registration_path, class: 'post'
    %nav.side-warap
      %ul.side-warap__bar
        %li
          %h2
            .side-warap__bar_parent
              %i.fa.fa-bars.tag-icon
          %ul.side-warap__bar_mega
            %li.side-warap__bar_mega_list
              %h3
                北海道地方
              %ul.side-warap__bar_mega_list_second
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "松前城", "/castles/23"
            %li.side-warap__bar_mega_list
              %h3
                東北地方
              %ul.side-warap__bar_mega_list_second
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "弘前城", "/castles/13"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "丸岡城", "/castles/14"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "白石城", "/castles/20"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "白河小峰城", "/castles/21"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "会津若松城", "/castles/24"
            %li.side-warap__bar_mega_list
              %h3
                関東地方
              %ul.side-warap__bar_mega_list_second
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "小田原城", "/castles/27"
            %li.side-warap__bar_mega_list
              %h3
                中部地方
              %ul.side-warap__bar_mega_list_second
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "名古屋城", "/castles/3"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "岐阜城", "/castles/6"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "犬山城", "/castles/10"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "松本城", "/castles/8"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "上田城", "/castles/12"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "掛川城", "/castles/22"
            %li.side-warap__bar_mega_list
              %h3
                近畿地方
              %ul.side-warap__bar_mega_list_second
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "大阪城" , "/castles/1"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "姫路城", "/castles/2"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "彦根城", "/castles/4"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "竹田城跡", "/castles/7"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "二条城", "/castles/11"
            %li.side-warap__bar_mega_list
              %h3
                中国地方
              %ul.side-warap__bar_mega_list_second
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "松江城", "/castles/15"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "備中松山城", "/castles/16"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "広島城", "/castles/25"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "岡山城", "/castles/26"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "福山城", "/castles/28"
            %li.side-warap__bar_mega_list
              %h3
                四国地方
              %ul.side-warap__bar_mega_list_second
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "伊予松山城", "/castles/5"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "丸亀城", "/castles/17"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "宇和島城", "/castles/18"
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "高知城", "/castles/19"
            %li.side-warap__bar_mega_list
              %h3
                九州地方
              %ul.side-warap__bar_mega_list_second
                %li.side-warap__bar_mega_list_second_post
                  .side-warap__bar_mega_list_second_post_category
                    = link_to "熊本城", "/castles/9"

app/views/castles/_under.html.haml
%nav.footer_clip_frame
  %ul
    %li.menu
      = link_to '1', '/',{class: "page-figure"}
    %li.menu
      = link_to '2', 'twopage',{class: "page-number"}

    %span.page-number-dots ...
    
    %li.menu
      = link_to '3', 'threepage',{class: "page-number"}
    %li.menu
      = link_to 'next', 'twopage',{class: "page-number"}

app/views/castles/index.html.haml
.wrapper
  =render 'topp'
  
  .top-inner
    .top-inner_clip
      %ul.category
        %li.category-web
          .figure
            = link_to image_tag("/assets/gaikan_003-2-1.jpg",width:"400",height: "300"), "/castles/1"
            %p 大阪城
        %li.category-web
          .figure
            = link_to image_tag("/assets/22106-06ufbtXC7xBz19vb02yE_lrg_re.jpg",width: "400",height: "300"),"/castles/2"
            %p 姫路城
        %li.category-web
          .figure
            = link_to image_tag("/assets/nagoyajo-sakematsuri1.jpg",width: "400",height: "300"),"/castles/3"
            %p 名古屋城
        %li.category-web
          .figure
            = link_to image_tag("/assets/pic30_06main.jpg",width: "400",height: "300"),"/castles/4"
            %p 彦根城
        %li.category-web
          .figure
            = link_to image_tag("/assets/matuyama.jpeg",width: "400",height: "300"),"/castles/5"
            %p 伊予松山城
        %li.category-web
          .figure
            = link_to image_tag("/assets/100174.jpg",width:"400",height: "300"),"/castles/6"
            %p 岐阜城
        %li.category-web
          .figure
            = link_to image_tag("/assets/600px-竹田城.jpeg",width: "400",height: "300"), "/castles/7"
            %p 竹田城跡
        %li.category-web
          .figure
            = link_to image_tag("/assets/130608_Matsumoto_Castle_Matsumoto_Nagano_pref_Japan02bs4.jpg", width: "400", height: "300"), "/castles/8"
            %p 松本城
        %li.category-web
          .figure
            = link_to image_tag("/assets/熊本城.jpeg",width: "400", height: "300"), "/castles/9"
            %p 熊本城
        %li.category-web
          .figure
            = link_to image_tag("/assets/犬山城.jpeg",width: "400",height: "300"), "/castles/10"
            %p 犬山城
        %li.category-web
          .figure
            = link_to image_tag("/assets/1920px-Nijo-jo_Ninomaru-goten_2009.jpg",width: "400", height: "300"), "/castles/11"
            %p 二条城
        %li.category-web
          .figure
            = link_to image_tag("/assets/1920px-Ueda_Castle_Amagafuchi.jpg",width: "400", height: "300"), "/castles/12"
            %p 上田城
      -# = paginate(@citadel)
    .footer_clip
      =render 'under'

app/views/castles/show.html.haml
.wrapper
  =render 'castles/topp'

  .name
    .name__header
      %h1.name__header_siromei
        = @citadel.name
    .name__header__adress
      %i.fa.fa-map-marker.name__header__adress_mark
      .name__header__adress_sales
        = @citadel.address
      %i.fa.fa-clock-o.name__header__adress_clock
      .name__header__adress_time
        = @citadel.time

  .castle-photo
    .castle-photo__box
      = image_tag(@citadel.image)

  .detail
    .detail__point
      .detail__point_title 見所
      .detail__point_description
        %span
          = @citadel.text

      -# .detail__point_detour.contory 寄り道
    .detail__history
      .detail__history_title 詳細
      .detail__history_comment
        %span
          = @citadel.detail
      -# .detail__history_money.fee 入場料
    .detail__map
      .detail__map_title お問い合わせ
      .detail__map_paste
        %iframe{allowfullscreen:  "", frameborder:  "0", :height => "450", src: @citadel.map, style: "border:0", width: "600"}
      .detail__map_adress
        %i.fa.fa-map-marker.detail__map_adress_mark
        %span.detail__map_adress_code
          = @citadel.address

  .comment

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Castle
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"}
  %body
    = yield

app/views/posts/index.html.haml
%h1 コメントサンプル
- if user_signed_in?
  = link_to "ログアウト", destroy_user_session_path, :method => :delete
  = link_to "マイページへ", user_path(current_user.id)
  %h2 投稿する
  = form_for @post do |f|
    = f.text_field :content
    = f.submit
  %hr/
  %h2 投稿一覧
  - @posts.each do |post|
    %a{:href => "/users/#{post.user.id}"}= post.user.email
    %p
      %a{:href => "/posts/#{post.id}"}= post.content
- else
  = link_to "ユーザー登録", new_user_registration_path
  = link_to "ログイン", new_user_session_path

app/views/posts/show.html.haml
%h1 投稿詳細ページ
%h3= @post.user.email
%h3= @post.content
= link_to "ホームへ戻る", posts_path

app/views/threepage/_under.html.haml
%nav.footer_clip_frame
  %ul
    %li.menu
      = link_to 'prev', '/twopage',{class:"send-page"}
    %li.menu
      = link_to '1', '/',{class: "page-number"}

    %span.page-number-dots ...
    
    %li.menu
      = link_to '2', 'twopage',{class: "page-number"}
    %li.menu
      = link_to '3', 'threepage',{class: "page-figure"}

app/views/threepage/index.html.haml
.wrapper
  =render 'castles/topp'
  
  .top-inner
    .top-inner_clip
      %ul.category
        %li.category-web
          .figure
            = link_to image_tag("/assets/500px-Hiroshima-castle-daihonei.jpg",width: "400",height: "300"), "/castles/25"
            %p 広島城
        %li.category-web
          .figure
            = link_to image_tag("/assets/520px-Okayama_Castle_02.jpg",width: "400",height: "300"), "/castles/26"
            %p 岡山城
        %li.category-web
          .figure
            = link_to image_tag("/assets/小田原城.jpeg",width: "400",height: "300"), "/castles/27"
            %p 小田原城
        %li.category-web
          .figure
            = link_to image_tag("/assets/520px-Fukuyamajyou7055.jpeg",width: "400",height: "300"), "/castles/28"
            %p 福山城
            
    .footer_clip
      =render 'under'

app/views/twopage/_under.html.haml
%nav.footer_clip_frame
  %ul
    %li.menu
      = link_to 'prev', '/',{class:"send-page"}
    %li.menu
      = link_to '1', '/',{class: "page-number"}

    %span.page-number-dots ...
    
    %li.menu
      = link_to '2', 'twopage',{class: "page-figure"}
    %li.menu
      = link_to '3', 'threepage',{class: "page-number"}
    %li.menu
      = link_to 'next', 'threepage',{class: "send-page"}

app/views/twopage/index.html.haml
.wrapper
  =render 'castles/topp'
  
  .top-inner
    .top-inner_clip
      %ul.category
        %li.category-web
          .figure
            = link_to image_tag("/assets/520px-Hirosaki-castle_Aomori_JAPAN.jpg",width:"400",height:"300"), "/castles/13"
            %p 弘前城
        %li.category-web
          .figure
            = link_to image_tag("/assets/520px-Maruoka_Castle_20100529-01.jpg",width: "400",height: "300"), "/castles/14"
            %p 丸岡城
        %li.category-web
          .figure
            = link_to image_tag("/assets/600px-150321_Matsue_Castle_Matsue_Shimane_pref_Japan01bs.jpg",width: "400",height: "300"), "/castles/15"
            %p 松江城
        %li.category-web
          .figure
            = link_to image_tag("/assets/520px-Bitchu_Matsuyama_Castle_1.jpeg",width: "400",height: "300"), "/castles/16"
            %p 備中松山城
        %li.category-web
          .figure
            = link_to image_tag("/assets/2.jpeg",width: "400",height: "300"), "/castles/17"
            %p 丸亀城
        %li.category-web
          .figure
            = link_to image_tag("/assets/520px-Uwazimacastle_tensyu.jpeg",width: "400",height: "300"), "/castles/18"
            %p 宇和島城
        %li.category-web
          .figure
            = link_to image_tag("/assets/520px-Kochi_Castle09.jpeg",width: "400", height: "300"), "/castles/19"
            %p 高知城
        %li.category-web
          .figure
            = link_to image_tag("/assets/520px-Shiroishi_Castle.jpeg",width: "400", height: "300"), "/castles/20"
            %p 白石城
        %li.category-web
          .figure
            = link_to image_tag("/assets/500px-Shirakawa_Komine_Castle_20100625-01.jpg",width: "400",height: "300"), "/castles/21"
            %p 白河小峰城
        %li.category-web
          .figure
            = link_to image_tag("/assets/520px-Kakegawajo.jpg",width: "400",height: "300"), "/castles/22"
            %p 掛川城
        %li.category-web
          .figure
            = link_to image_tag("/assets/520px-MatsumaeCastle.jpg",width: "400", height: "300"), "/castles/23"
            %p 松前城
        %li.category-web
          .figure
            = link_to image_tag("/assets/520px-March_2011_The_Aizu-Wakamatsu_Castle.jpg",width: "400",height: "300"), "/castles/24"
            %p 会津若松城

    .footer_clip
      =render 'under'